### ISSUE TITLE
Does not show up in jupyterlab

### ISSUE THREAD

**Issue by kmader** [chestrays/cornerstone_widget#10]
javascript console error message
```Error: Object 'jupyter.widget' not found in registry```

![image](https://user-images.githubusercontent.com/116120/45215133-c84e0a00-b29c-11e8-9447-0b9204e4a920.png)

**Comment by kmader** [comment]
seems to be related to https://github.com/jupyter-widgets/ipywidgets/issues/1534

**Comment by kmader** [comment]
@joshy  this seems to change the error message in jupyterlab but it still appears not to be fully registered: https://github.com/chestrays/cornerstone_widget/blob/4b0f96bfcec523dd29a8c2fbb3079ab00b348739/binder/postBuild#L1-L6

**Comment by kmader** [comment]
@joshy jquery isn't automatically provided in jupyterlab and the jupyterlab manager needs to be installed, can you check if this now works for you?

**Comment by joshy** [comment]
@kmader It is still not working 
![image](https://user-images.githubusercontent.com/170219/45217923-2501f280-b2a6-11e8-889d-1304a90ecef5.png)

**Comment by joshy** [comment]
@kmader Could this be the issue?: https://github.com/jupyter-widgets/ipyleaflet/issues/95#issuecomment-358504310

**Comment by kmader** [comment]
@joshy no because they are both defined and it works in binder
https://github.com/chestrays/cornerstone_widget/blob/573f8e4c588858da9b7e88e166f8cf258af6a34c/js/lib/cs_widget.js#L19-L20

**Comment by irtazas** [comment]
hi kmader. did you find a solution to this problem? I'm having the same issue.

**Comment by betatim** [comment]
The problem has been solved here. Probably best to compare how things are setup on your side and how things are setup for mybinder.org: https://github.com/chestrays/cornerstone_widget/tree/master/binder
